### ISSUE TITLE
File Structure feature not work

### ISSUE THREAD

**Issue by fzzr-** [TiVo/intellij-haxe#213]
Idea's "File Structure" feature fully & totally not work.

log:
```log
com.intellij.ide.structureView.TreeBasedStructureViewBuilder.createStructureViewModel(Lcom/intellij/openapi/editor/Editor;)Lcom/intellij/ide/structureView/StructureViewModel;
java.lang.AbstractMethodError: com.intellij.ide.structureView.TreeBasedStructureViewBuilder.createStructureViewModel(Lcom/intellij/openapi/editor/Editor;)Lcom/intellij/ide/structureView/StructureViewModel;
	at com.intellij.ide.structureView.TreeBasedStructureViewBuilder.createStructureView(TreeBasedStructureViewBuilder.java:50)
	at com.intellij.ide.actions.ViewStructureAction.createPopup(ViewStructureAction.java:106)
	at com.intellij.ide.actions.ViewStructureAction.actionPerformed(ViewStructureAction.java:75)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$3.performAction(IdeKeyEventDispatcher.java:586)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:637)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.d(IdeKeyEventDispatcher.java:476)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:212)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:538)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

and another log:
```log
2015-04-05 21:50:03,261 [37304477]  ERROR - llij.ide.plugins.PluginManager - com.intellij.ide.structureView.TreeBasedStructureViewBuilder.createStructureViewModel(Lcom/intellij/openapi/editor/Editor;)Lcom/intellij/ide/structureView/StructureViewModel; 
java.lang.AbstractMethodError: com.intellij.ide.structureView.TreeBasedStructureViewBuilder.createStructureViewModel(Lcom/intellij/openapi/editor/Editor;)Lcom/intellij/ide/structureView/StructureViewModel;
	at com.intellij.ide.structureView.TreeBasedStructureViewBuilder.createStructureView(TreeBasedStructureViewBuilder.java:50)
	at com.intellij.ide.actions.ViewStructureAction.createPopup(ViewStructureAction.java:106)
	at com.intellij.ide.actions.ViewStructureAction.actionPerformed(ViewStructureAction.java:75)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$3.performAction(IdeKeyEventDispatcher.java:586)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:637)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.d(IdeKeyEventDispatcher.java:476)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:212)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:538)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
2015-04-05 21:50:03,262 [37304478]  ERROR - llij.ide.plugins.PluginManager - IntelliJ IDEA (Cassiopeia) IU-141.498.1  Build #IU-141.498.1 
2015-04-05 21:50:03,262 [37304478]  ERROR - llij.ide.plugins.PluginManager - JDK: 1.8.0_20 
2015-04-05 21:50:03,262 [37304478]  ERROR - llij.ide.plugins.PluginManager - VM: Java HotSpot(TM) 64-Bit Server VM 
2015-04-05 21:50:03,262 [37304478]  ERROR - llij.ide.plugins.PluginManager - Vendor: Oracle Corporation 
2015-04-05 21:50:03,262 [37304478]  ERROR - llij.ide.plugins.PluginManager - OS: Mac OS X 
2015-04-05 21:50:03,262 [37304478]  ERROR - llij.ide.plugins.PluginManager - Last Action: FileStructurePopup 
```

**Comment by EBatTiVo** [comment]
This works for me.  What's the environment, and what version of the plugin do you have?

**Comment by fzzr-** [comment]
@EBatTiVo Latest release 0.9.3. Not work.
`com.intellij.ide.structureView.TreeBasedStructureViewBuilder.createStructureViewModel(Lcom/intellij/openapi/editor/Editor;)Lcom/intellij/ide/structureView/StructureViewModel;`

Error when show the «Structure» panel:
```log
com.intellij.ide.structureView.TreeBasedStructureViewBuilder.createStructureViewModel(Lcom/intellij/openapi/editor/Editor;)Lcom/intellij/ide/structureView/StructureViewModel;
java.lang.AbstractMethodError: com.intellij.ide.structureView.TreeBasedStructureViewBuilder.createStructureViewModel(Lcom/intellij/openapi/editor/Editor;)Lcom/intellij/ide/structureView/StructureViewModel;
	at com.intellij.ide.structureView.TreeBasedStructureViewBuilder.createStructureView(TreeBasedStructureViewBuilder.java:50)
	at com.intellij.ide.impl.StructureViewWrapperImpl.rebuild(StructureViewWrapperImpl.java:315)
	at com.intellij.ide.impl.StructureViewWrapperImpl$6.run(StructureViewWrapperImpl.java:253)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:320)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:310)
	at com.intellij.util.ui.update.MergingUpdateQueue$2.run(MergingUpdateQueue.java:254)
	at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2344)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:266)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:227)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:217)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:351)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:332)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:749)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:702)
	at java.awt.EventQueue$3.run(EventQueue.java:696)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:719)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

Error when show the «File Structure» quick panel (popup like autocomplete popup) :
```
com.intellij.ide.structureView.TreeBasedStructureViewBuilder.createStructureViewModel(Lcom/intellij/openapi/editor/Editor;)Lcom/intellij/ide/structureView/StructureViewModel;
java.lang.AbstractMethodError: com.intellij.ide.structureView.TreeBasedStructureViewBuilder.createStructureViewModel(Lcom/intellij/openapi/editor/Editor;)Lcom/intellij/ide/structureView/StructureViewModel;
	at com.intellij.ide.structureView.TreeBasedStructureViewBuilder.createStructureView(TreeBasedStructureViewBuilder.java:50)
	at com.intellij.ide.actions.ViewStructureAction.createPopup(ViewStructureAction.java:106)
	at com.intellij.ide.actions.ViewStructureAction.actionPerformed(ViewStructureAction.java:75)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$3.performAction(IdeKeyEventDispatcher.java:586)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:637)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:476)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:212)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:538)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```
![screen shot 2015-05-20 at 13 04 05](https://cloud.githubusercontent.com/assets/888526/7723392/eb020834-fef0-11e4-91ef-67573e32654e.png)

**Comment by EBatTiVo** [comment]
From the Java documentation:

> public class AbstractMethodError
> extends IncompatibleClassChangeError
> Thrown when an application tries to call an abstract method. Normally, this error is caught by the compiler; this error can only occur at run time if the definition of some class has incompatibly changed since the currently executing method was last compiled.

Alexander, are you running your own builds?  Or perhaps running an EAP release?  There might be a version mismatch problem between the IDEA SDK used to compile the plugin and the version of IDEA that you are using.

We're definitely going to need specific version information for the plugin (or your build of it, in which case, give us the git hash) and which IDEA you are running.  

If you are running your own build, this problem may go away by using "Rebuild Project" or the ant "package" target (which always run a complete build).

**Comment by fzzr-** [comment]
No, that logs from Idea Community Edition 14.1.3 (not EAP) on OS X 10.10.4.
Used version of plugin is [0.9.3 CE](https://github.com/TiVo/intellij-haxe/releases/tag/0.9.3). Sorry, I don't know why it happening. Mb. it because one of other installed plugins or missed one. E.g.: currently I don't have installed UI-Designer (for Swing).
![screen shot 2015-05-22 at 12 44 41](https://cloud.githubusercontent.com/assets/888526/7768130/ce6200bc-0080-11e5-8e80-5ae04f63d352.png)

**Comment by EBatTiVo** [comment]
Ah.  I think this might be because the 0.9.3 ant build didn't have all of the same files included in it that the IDEA build usually does.  In particular, the uiDesigner/core files which translate the GUI .forms files were missing.  I've just fixed that recently, so the next release on Monday will likely fix this.  

Since I don't test on a machine that isn't set up to build the plugin, I would probably never see the bug. Maybe there's something I can do about that.

**Comment by fzzr-** [comment]
I see it! Thanks, it works now!
Using «0.9.4 Community Release, Patch 1 for Idea 14.1» on Idea Community Edition 14.1.3 (JRE: 1.8.0_40)
