### ISSUE TITLE
Compatibility with Idea 15

### ISSUE THREAD

**Issue by fzzr-** [TiVo/intellij-haxe#313]
* Idea Ultimate 15 EAP
* Flash AIR Project

Happens on init Haxe-plugin.

```log
NATIVE_MAC_CHOOSER_SHOW_HIDDEN_FILES
java.lang.NoSuchFieldError: NATIVE_MAC_CHOOSER_SHOW_HIDDEN_FILES
	at com.intellij.plugins.haxe.config.sdk.HaxeSdkType.getHomeChooserDescriptor(HaxeSdkType.java:120)
	at com.intellij.openapi.projectRoots.ui.SdkEditor.a(SdkEditor.java:286)
	at com.intellij.openapi.projectRoots.ui.SdkEditor.reset(SdkEditor.java:242)
	at com.intellij.openapi.projectRoots.ui.SdkEditor.a(SdkEditor.java:110)
	at com.intellij.openapi.projectRoots.ui.SdkEditor.<init>(SdkEditor.java:93)
	at com.intellij.openapi.roots.ui.configuration.projectRoot.JdkConfigurable.createSdkEditor(JdkConfigurable.java:57)
	at com.intellij.openapi.roots.ui.configuration.projectRoot.JdkConfigurable.<init>(JdkConfigurable.java:51)
	at com.intellij.openapi.roots.ui.configuration.projectRoot.JdkListConfigurable.loadTree(JdkListConfigurable.java:128)
	at com.intellij.openapi.roots.ui.configuration.projectRoot.BaseStructureConfigurable.reset(BaseStructureConfigurable.java:269)
	at com.intellij.openapi.roots.ui.configuration.projectRoot.JdkListConfigurable.reset(JdkListConfigurable.java:168)
	at com.intellij.openapi.roots.ui.configuration.ProjectStructureConfigurable.reset(ProjectStructureConfigurable.java:374)
	at com.intellij.openapi.options.ex.SingleConfigurableEditor.<init>(SingleConfigurableEditor.java:67)
	at com.intellij.openapi.options.ex.SingleConfigurableEditor.<init>(SingleConfigurableEditor.java:89)
	at com.intellij.openapi.options.ex.SingleConfigurableEditor.<init>(SingleConfigurableEditor.java:104)
	at com.intellij.ide.actions.ShowStructureSettingsAction$1.<init>(ShowStructureSettingsAction.java:43)
	at com.intellij.ide.actions.ShowStructureSettingsAction.showDialog(ShowStructureSettingsAction.java:43)
	at com.intellij.ide.actions.ShowStructureSettingsAction.actionPerformed(ShowStructureSettingsAction.java:38)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$3.performAction(IdeKeyEventDispatcher.java:595)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:646)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.d(IdeKeyEventDispatcher.java:485)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:215)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:626)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:392)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

![screen shot 2015-06-22 at 16 18 00](https://cloud.githubusercontent.com/assets/888526/8282600/87169578-18fa-11e5-921d-969b9fcf2712.png)

**Comment by fzzr-** [comment]
And when I try open Project Structure:

```log
module editors was not disposed
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:115)
	at com.intellij.openapi.roots.ui.configuration.ModulesConfigurator$5.run(ModulesConfigurator.java:192)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:975)
	at com.intellij.openapi.roots.ui.configuration.ModulesConfigurator.resetModuleEditors(ModulesConfigurator.java:188)
	at com.intellij.openapi.roots.ui.configuration.projectRoot.StructureConfigurableContext.reset(StructureConfigurableContext.java:176)
	at com.intellij.openapi.roots.ui.configuration.ProjectStructureConfigurable.reset(ProjectStructureConfigurable.java:362)
	at com.intellij.openapi.options.ex.SingleConfigurableEditor.<init>(SingleConfigurableEditor.java:67)
	at com.intellij.openapi.options.ex.SingleConfigurableEditor.<init>(SingleConfigurableEditor.java:89)
	at com.intellij.openapi.options.ex.SingleConfigurableEditor.<init>(SingleConfigurableEditor.java:104)
	at com.intellij.ide.actions.ShowStructureSettingsAction$1.<init>(ShowStructureSettingsAction.java:43)
	at com.intellij.ide.actions.ShowStructureSettingsAction.showDialog(ShowStructureSettingsAction.java:43)
	at com.intellij.ide.actions.ShowStructureSettingsAction.actionPerformed(ShowStructureSettingsAction.java:38)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$3.performAction(IdeKeyEventDispatcher.java:595)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:646)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.d(IdeKeyEventDispatcher.java:485)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:215)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:626)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:392)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by as3boyan** [comment]
What IDEA 15 they are so fast

**Comment by grisevg** [comment]
Once a year

**Comment by EBatTiVo** [comment]
IDEA 14.1.4 was just released.  IDEA 15 is in EAP, which is not a priority.

The exception is a missing field, so either the field name changed or was dropped from the API.

**Comment by indolering** [comment]
15 is now the current release, bug should at least be reprioritized.

**Comment by justspamjustin** [comment]
+1

**Comment by kaero** [comment]
:+1:
New project creation is fine except, i cann't select SDK %) Button to choose SDK in master or project settings do nothing.

**Comment by haysclark** [comment]
+1 will try compiling the plug-in locally and see what's up.

**Comment by bynuff** [comment]
+1

**Comment by realcraig** [comment]
+1

**Comment by grisevg** [comment]
+1 =S

**Comment by indolering** [comment]
@haysclark is IDEA 14 + JDK 8 working?

**Comment by EBatTiVo** [comment]
Up until this point, we've continued to compile the plugin for IDEA 14 using JDK6.  I'm running IDEA14 and the plugin with JDK8 with no issues. I haven't tried running IDEA 15 yet.

**Comment by fzzr-** [comment]
![screen shot 2016-01-07 at 14 47 40](https://cloud.githubusercontent.com/assets/888526/12169970/e9286d3c-b54d-11e5-8d76-ebae02a8feec.png)

```log
2016-01-07 14:49:00,999 [ 163874]  ERROR - aemon.impl.PassExecutorService - IntelliJ IDEA 15.0.2  Build #IC-143.1184.17 
2016-01-07 14:49:00,999 [ 163874]  ERROR - aemon.impl.PassExecutorService - JDK: 1.8.0_40-release 
2016-01-07 14:49:00,999 [ 163874]  ERROR - aemon.impl.PassExecutorService - VM: OpenJDK 64-Bit Server VM 
2016-01-07 14:49:00,999 [ 163874]  ERROR - aemon.impl.PassExecutorService - Vendor: JetBrains s.r.o 
2016-01-07 14:49:00,999 [ 163874]  ERROR - aemon.impl.PassExecutorService - OS: Mac OS X 
2016-01-07 14:49:00,999 [ 163874]  ERROR - aemon.impl.PassExecutorService - Last Action: ShowProjectStructureSettings 
2016-01-07 14:49:00,999 [ 163874]  ERROR - aemon.impl.PassExecutorService - com/intellij/psi/impl/source/tree/SourceUtil 
java.lang.NoClassDefFoundError: com/intellij/psi/impl/source/tree/SourceUtil
	at com.intellij.plugins.haxe.lang.psi.impl.HaxeReferenceImpl.getQualifiedName(HaxeReferenceImpl.java:798)
	at com.intellij.plugins.haxe.lang.psi.HaxeResolver.resolveImportFile(HaxeResolver.java:241)
	at com.intellij.plugins.haxe.lang.psi.HaxeResolver.resolve(HaxeResolver.java:73)
	at com.intellij.plugins.haxe.lang.psi.HaxeResolver.resolve(HaxeResolver.java:45)
	at com.intellij.psi.impl.source.resolve.ResolveCache$3.compute(ResolveCache.java:142)
	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:139)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:213)
	at com.intellij.plugins.haxe.lang.psi.impl.HaxeReferenceImpl.multiResolve(HaxeReferenceImpl.java:177)
	at com.intellij.plugins.haxe.lang.psi.impl.HaxeReferenceImpl.resolveToComponentName(HaxeReferenceImpl.java:198)
	at com.intellij.plugins.haxe.ide.annotator.HaxeColorAnnotator.annotate(HaxeColorAnnotator.java:61)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:162)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:103)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:354)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.access$100(GeneralHighlightingPass.java:65)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass$3.run(GeneralHighlightingPass.java:283)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:308)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.access$200(GeneralHighlightingPass.java:65)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass$4.run(GeneralHighlightingPass.java:314)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:87)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:311)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:280)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:219)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:82)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:67)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:444)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1169)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:435)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:432)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:408)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:206)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:108)
```

**Comment by fzzr-** [comment]
:sob:

**Comment by fzzr-** [comment]
It's a Intellij Idea 15 Community Edition with __bundled JRE 1.8u40 custom build__ on OS X 10.11.2.

**Comment by EBatTiVo** [comment]
Fixed: 03772de209053a5e3e993e34086108d4096374a6   Not yet tested on a Mac. PR #386 

Will close when tested.

**Comment by eliasku** [comment]
I use IDEA 15 + Haxe Support 0.9.9 release
Looks like all works fine (at least IDEA 15 support is implemented)

**Comment by EBatTiVo** [comment]
Let's just close this.  @fzzr- please reopen if it isn't working for you.  Both @eliasku and myself have this working on the Mac.
