### ISSUE TITLE
[0.10.1 RC2] NPE in HaxeLookupElement

### ISSUE THREAD

**Issue by eliasku** [TiVo/intellij-haxe#496]
Just found in logs for my project setup. Project view Scroll starts jumping to fixed position. Also while scrolling because of high amount of NPE memory consuming is growing fast. I will fix it if will have free time.
 
```
2016-10-11 20:22:26,289 [4021853]  ERROR - .psi.impl.HaxeNamedElementImpl - IntelliJ IDEA 2016.2.3  Build #IU-162.1812.17 
2016-10-11 20:22:26,289 [4021853]  ERROR - .psi.impl.HaxeNamedElementImpl - JDK: 1.8.0_112-release 
2016-10-11 20:22:26,289 [4021853]  ERROR - .psi.impl.HaxeNamedElementImpl - VM: OpenJDK 64-Bit Server VM 
2016-10-11 20:22:26,289 [4021853]  ERROR - .psi.impl.HaxeNamedElementImpl - Vendor: JetBrains s.r.o 
2016-10-11 20:22:26,289 [4021853]  ERROR - .psi.impl.HaxeNamedElementImpl - OS: Mac OS X 
2016-10-11 20:22:26,289 [4021853]  ERROR - .psi.impl.HaxeNamedElementImpl - Last Action: SaveAll 
2016-10-11 20:22:26,289 [4021853]  ERROR - .psi.impl.HaxeNamedElementImpl - Current Command:  
2016-10-11 20:22:26,289 [4021853]  ERROR - .psi.impl.HaxeNamedElementImpl - null 
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:127)
	at com.intellij.plugins.haxe.lang.psi.impl.HaxeNamedElementImpl.getName(HaxeNamedElementImpl.java:79)
	at com.intellij.plugins.haxe.ide.HaxeLookupElement.getLookupString(HaxeLookupElement.java:65)
	at com.intellij.codeInsight.lookup.LookupElement.getAllLookupStrings(LookupElement.java:46)
	at com.intellij.codeInsight.completion.impl.CamelHumpMatcher.a(CamelHumpMatcher.java:74)
	at com.intellij.codeInsight.completion.impl.CamelHumpMatcher.prefixMatches(CamelHumpMatcher.java:70)
	at com.intellij.codeInsight.completion.LegacyCompletionContributor.a(LegacyCompletionContributor.java:73)
	at com.intellij.codeInsight.completion.LegacyCompletionContributor.a(LegacyCompletionContributor.java:124)
	at com.intellij.codeInsight.completion.LegacyCompletionContributor.processReferences(LegacyCompletionContributor.java:107)
	at com.intellij.codeInsight.completion.LegacyCompletionContributor.completeReference(LegacyCompletionContributor.java:69)
	at com.intellij.codeInsight.completion.LegacyCompletionContributor.fillCompletionVariants(LegacyCompletionContributor.java:52)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:81)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:132)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:125)
	at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor$2.addCompletions(LiveTemplateCompletionContributor.java:90)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:155)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:81)
	at com.intellij.codeInsight.completion.CompletionService.performCompletion(CompletionService.java:110)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.a(CompletionProgressIndicator.java:776)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.access$500(CompletionProgressIndicator.java:90)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator$1CalculateItems.run(CompletionProgressIndicator.java:758)
	at com.intellij.codeInsight.completion.AsyncCompletion.b(CompletionThreading.java:87)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:856)
	at com.intellij.codeInsight.completion.AsyncCompletion.a(CompletionThreading.java:84)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:494)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:155)
	at com.intellij.codeInsight.completion.AsyncCompletion.a(CompletionThreading.java:82)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:308)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by eliasku** [comment]
I've debugging very long time and catch exception `ProcessCanceledException`. Because we catch all Throwable exceptions - we had rethrowing it up by `LOG.error` call.

@EBatTiVo  I think we should change `HaxeNamedElementImpl:74`:

```
@Override
  public String getName() {
    try {
      return getIdentifier().getText();
    }
    catch (Throwable t) {
      // log & swallow
      LOG.error(t.getMessage());
      return "";
    }
  }
```

to this:

```
  @Override
  public String getName() {
    try {
      return getIdentifier().getText();
    }
    catch (ProcessCanceledException cancelled) {}
    catch (Throwable t) {
      // log & swallow
      LOG.error(t.getMessage());
    }
    return "";
  }
```

What do you think? Sometimes when ProcessCancel exception are caught by us and we're rethrowing different exception with LOG.error and IDEA starts hanging up.

**Comment by EBatTiVo** [comment]
I don't fully understand:  I see that the old code would log the error, but then it shouldn't have thrown another.  Are you saying that LOG.error is, itself, failing and throwing a different exception?

I would prefer to re-throw the ProcessCanceledException up the call stack than to ignore it and keep running as if the command weren't canceled.

**Comment by eliasku** [comment]
@EBatTiVo 

Yes, you're right. But problem is still here. Let's inspect Idea implementation:

http://grepcode.com/file/repository.grepcode.com/java/ext/com.jetbrains/intellij-idea/12.0/com/intellij/idea/IdeaLogger.java#115

```
    if (t instanceof ProcessCanceledException) {
      myLogger.error(new Throwable("Do not log ProcessCanceledException").initCause(t));
      throw (ProcessCanceledException)t;
    }
```

Seems like they suggest to skip cancellation exception from logging. Because it unnecessary and not provide any useful information.

Problems are still here. 
1. Log file growing very fast (and these exceptions are useless for analysis)
2. Heap is growing because of point 1.

Yes, I think we need to catch cancellation exception and re-throw it instead of logging error.

**Comment by EBatTiVo** [comment]
Yeah, the default logger implementation (which I guess we're not using) also changes the exception into an AssertionError and rethrows that.

What do you think if we do this:?
```java
@Override
  public String getName() {
    try {
      return getIdentifier().getText();
    }
    catch (ProcessCanceledException cancelled) {
        Log.debug("Rethrowing ProcessCanceledException");
        throw( cancelled );
    }
    catch (Throwable t) {
      // log and rethrow
      LOG.error(t);
    }
    return "";
  }
```

If we really want to swallow the exception in the `catch (Throwable)` clause, then we need to call LOG.warn or a lesser severity logging call.  Logger.error always seems to turn the issue into a different error.

**Comment by EBatTiVo** [comment]
The point of LOG.debug is only that we can see it happening, when we are debugging.  Otherwise, it won't go into the log.  (Unless I am mis-understanding how Logger is working.)

**Comment by EBatTiVo** [comment]
On, the other hand, we could do this:
```java
@Override
  public String getName() {
    try {
        HaxeIdentifier id = getIdentifier();
        if (null != id) {
            return getText();
        }
        // Maybe log a debug warning here...
        //    LOG.debug("Empty string encountered in HaxePsiElement.");
        // Or, if we want the call stack.
        //    LOG.warn("Empty string encountered in HaxePsiElement.");
        return "";
    }
    catch (ProcessCanceledException cancelled) {
        LOG.debug("Rethrowing ProcessCanceledException");
        throw( cancelled );
    }
    catch (Throwable t) {
      // log and rethrow
      LOG.error(t);
    }
    return "";
  }
```

**Comment by eliasku** [comment]
Since `getIdentifier` is not-null by annotation, `getText` could return null-string, but I noticed that `getName` is nullable...
Could we rewrite that to the most simplest way? 

```java
  @Override
  public String getName() {
    return getIdentifier().getName();
  }
```

**Comment by EBatTiVo** [comment]
I guess so.  I don't put much stock in annotations, because they are too fluid: Engineers change them on a whim and don't bother to find and fix up code that relied upon the contract.  Consequently, I usually ignore them (and end up writing bloated code).

Looking back at the history for this file: @sganapavarapu1 changed the implementation from what you suggest to one similar to what we have now: 1ea2a13e8e81e0214965bc8803b9ed5bf813d7d4.  I'll see if he can remember why he made this change.

**Comment by sganapavarapu1** [comment]
https://github.com/TiVo/intellij-haxe/commit/1ea2a13e8e81e0214965bc8803b9ed5bf813d7d4

If my memory serves me right, this was made because getIdentifier() was sometimes returning null, resulting in NPE.

**Comment by EBatTiVo** [comment]
@eliasku So, Srikanth says that he rewrote the function because we were getting NPEs (in violation of the annotations).  My current thought is to do this:
```java
@Override
  public String getName() {
    try {
      return getIdentifier().getText();
    }
    catch (NullPointerException t) {
      // log & swallow - The annotations say @NotNull, but we get them anyway.
      LOG.debug(t.getMessage() + "Coercing to empty string.");
      return "";
    }
    // Let all other exceptions get thrown right past.
  }
```
Maybe this will be specific enough to solve the initial problem, but not stop real exceptions.

**Comment by EBatTiVo** [comment]
Closing, because we merged the fix.
