### ISSUE TITLE
NPE when running unit tests.

### ISSUE THREAD

**Issue by EBatTiVo** [TiVo/intellij-haxe#68]
Many unit tests throw an NPE while running.  The NPE has nothing to do with the code being tested; it is a configuration fault, near as I can tell.

Occurs on all tested repos (JetBrains/intellij-haxe/master, TiVo/intellij-haxe/master, TiVo/intellij-haxe/ClassHierarchy, EBatTiVo/intellij-haxe/ClassHierarchy).

To reproduce: Load the intellij-haxe project; Run the "HaxeTests" configuration.

The line of code throwing the NPE is:  (From WriteCommandAction.java)
<pre>
  public static boolean ensureFilesWritable(@NotNull final Project project, @NotNull final Collection&lt;PsiFile> psiFiles) {
    return FileModificationService.getInstance().preparePsiElementsForWrite(psiFiles);
  }
</pre>

What's happening is that FileModificationService.getInstance() is returning null.  Obviously, dereferencing that causes the NPE.  

FileModification service appears to be instantiated by adding a service to the LangExtensions.xml file.  The Haxe plugin doesn't have one of those.  I tried adding the stanza to the plugin.xml, but it did not fix the problem.

The appropriate stanza is:
<pre>
&lt;idea-plugin>
  &lt;extensions defaultExtensionNs="com.intellij">
    &lt;applicationService serviceInterface="com.intellij.codeInsight.FileModificationService"
                        serviceImplementation="com.intellij.codeInsight.CodeInsightUtilBase"/>
  &lt;/extensions>
&lt;/idea-plugin>
</pre>

Below is a typical exception stack:
<pre>
java.lang.RuntimeException: java.lang.NullPointerException
	at com.intellij.testFramework.fixtures.impl.CodeInsightTestFixtureImpl$18.run(CodeInsightTestFixtureImpl.java:1127)
	at com.intellij.util.ui.UIUtil.invokeAndWaitIfNeeded(UIUtil.java:2074)
	at com.intellij.testFramework.fixtures.impl.CodeInsightTestFixtureImpl.setUp(CodeInsightTestFixtureImpl.java:1119)
	at com.intellij.testFramework.fixtures.JavaCodeInsightFixtureTestCase.setUp(JavaCodeInsightFixtureTestCase.java:57)
	at com.intellij.testFramework.UsefulTestCase.defaultRunBare(UsefulTestCase.java:340)
	at com.intellij.testFramework.UsefulTestCase$3.run(UsefulTestCase.java:353)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:199)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:672)
	at java.awt.EventQueue.access$400(EventQueue.java:81)
	at java.awt.EventQueue$2.run(EventQueue.java:633)
	at java.awt.EventQueue$2.run(EventQueue.java:631)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:87)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:642)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:269)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:184)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:174)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:169)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
Caused by: java.lang.NullPointerException
	at com.intellij.openapi.command.WriteCommandAction.performWriteCommandAction(WriteCommandAction.java:106)
	at com.intellij.openapi.command.WriteCommandAction.access$000(WriteCommandAction.java:33)
	at com.intellij.openapi.command.WriteCommandAction$1.run(WriteCommandAction.java:80)
	at com.intellij.openapi.command.WriteCommandAction.execute(WriteCommandAction.java:85)
	at com.intellij.testFramework.fixtures.impl.HeavyIdeaTestFixtureImpl.a(HeavyIdeaTestFixtureImpl.java:148)
	at com.intellij.testFramework.fixtures.impl.HeavyIdeaTestFixtureImpl.setUp(HeavyIdeaTestFixtureImpl.java:102)
	at com.intellij.testFramework.fixtures.impl.CodeInsightTestFixtureImpl$18.run(CodeInsightTestFixtureImpl.java:1123)
	... 20 more
</pre>

TIR: STB-5630

**Comment by EBatTiVo** [comment]
> Also somewhere following Psi element is added:
> 
> `PARAMETER_LIST`
> `<empty list>`
> to FUNCTION_DECLARATION_WITH_ATTRIBUTES

Yes, I added the empty parameter list to help with processing class type parameters (generic notation).  That should be expected and added to the failing test.

**Comment by EBatTiVo** [comment]
The original problem was that the netty library wasn't included in the SDK dependencies.
