### ISSUE TITLE
Unresolved dependency error while running unit tests.

### ISSUE THREAD

**Issue by EBatTiVo** [TiVo/intellij-haxe#70]
Test: HaxeSourceRootDetectionTest

Occurs on JetBrains and TiVo repos.

The following error occurs, with follow-on NPEs, while running unit tests:
<pre>
ERROR: com.intellij.openapi.project.impl.ProjectManagerImpl has unsatisfied dependency: class com.intellij.ide.RecentProjectsManagerBase among unsatisfiable dependencies: [[class com.intellij.openapi.vfs.VirtualFileManager, class com.intellij.ide.RecentProjectsManagerBase, class com.intellij.openapi.progress.ProgressManager]] where AreaPicoContainer.MyPicoContainer[null] was the leaf container being asked for dependencies.
org.picocontainer.defaults.UnsatisfiableDependenciesException: com.intellij.openapi.project.impl.ProjectManagerImpl has unsatisfied dependency: class com.intellij.ide.RecentProjectsManagerBase among unsatisfiable dependencies: [[class com.intellij.openapi.vfs.VirtualFileManager, class com.intellij.ide.RecentProjectsManagerBase, class com.intellij.openapi.progress.ProgressManager]] where AreaPicoContainer.MyPicoContainer[null] was the leaf container being asked for dependencies.
	at org.picocontainer.defaults.ConstructorInjectionComponentAdapter.getGreediestSatisfiableConstructor(ConstructorInjectionComponentAdapter.java:191)
	at org.picocontainer.defaults.ConstructorInjectionComponentAdapter$1.run(ConstructorInjectionComponentAdapter.java:210)
	at org.picocontainer.defaults.ThreadLocalCyclicDependencyGuard.observe(ThreadLocalCyclicDependencyGuard.java:53)
	at org.picocontainer.defaults.ConstructorInjectionComponentAdapter.getComponentInstance(ConstructorInjectionComponentAdapter.java:248)
	at org.picocontainer.defaults.DecoratingComponentAdapter.getComponentInstance(DecoratingComponentAdapter.java:60)
	at org.picocontainer.defaults.CachingComponentAdapter.getComponentInstance(CachingComponentAdapter.java:58)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter$1.getComponentInstance(ComponentManagerImpl.java:530)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:590)
	at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:225)
	at com.intellij.util.pico.DefaultPicoContainer.getInstance(DefaultPicoContainer.java:212)
	at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:199)
	at org.picocontainer.defaults.BasicComponentParameter.resolveInstance(BasicComponentParameter.java:77)
	at org.picocontainer.defaults.ComponentParameter.resolveInstance(ComponentParameter.java:114)
	at org.picocontainer.defaults.ConstructorInjectionComponentAdapter.getConstructorArguments(ConstructorInjectionComponentAdapter.java:257)
	at org.picocontainer.defaults.ConstructorInjectionComponentAdapter$1.run(ConstructorInjectionComponentAdapter.java:217)
	at org.picocontainer.defaults.ThreadLocalCyclicDependencyGuard.observe(ThreadLocalCyclicDependencyGuard.java:53)
	at org.picocontainer.defaults.ConstructorInjectionComponentAdapter.getComponentInstance(ConstructorInjectionComponentAdapter.java:248)
	at org.picocontainer.defaults.DecoratingComponentAdapter.getComponentInstance(DecoratingComponentAdapter.java:60)
	at org.picocontainer.defaults.CachingComponentAdapter.getComponentInstance(CachingComponentAdapter.java:58)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter$1.getComponentInstance(ComponentManagerImpl.java:530)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:590)
	at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:225)
	at com.intellij.util.pico.DefaultPicoContainer.getInstance(DefaultPicoContainer.java:212)
	at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:199)
	at org.picocontainer.alternatives.AbstractDelegatingMutablePicoContainer.getComponentInstance(AbstractDelegatingMutablePicoContainer.java:75)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.getComponentFromContainer(ComponentManagerImpl.java:164)
	at com.intellij.openapi.application.impl.ApplicationImpl.getComponentFromContainer(ApplicationImpl.java:542)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.getComponent(ComponentManagerImpl.java:192)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.getComponent(ComponentManagerImpl.java:187)
	at com.intellij.openapi.fileEditor.FileDocumentManager.getInstance(FileDocumentManager.java:28)
	at com.intellij.openapi.vfs.impl.local.LocalFileSystemImpl$6.run(LocalFileSystemImpl.java:535)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:984)
	at com.intellij.openapi.vfs.impl.local.LocalFileSystemImpl.cleanupForNextTest(LocalFileSystemImpl.java:532)
	at com.intellij.testFramework.PlatformTestCase.cleanupApplicationCaches(PlatformTestCase.java:343)
	at com.intellij.testFramework.PlatformTestCase$4.run(PlatformTestCase.java:600)
	at com.intellij.openapi.application.impl.LaterInvocator$1.run(LaterInvocator.java:165)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:319)
</pre>

TIR: STB-5630

**Comment by EBatTiVo** [comment]
Fixed.  Not sure exactly when.  All dependency errors have been fixed as of this time because all tests are running (though some still have errors).
