### ISSUE TITLE
ClassHierarchy: HaxelibLibraryCache: java.lang.ArrayIndexOutOfBoundsException: 2

### ISSUE THREAD

**Issue by as3boyan** [TiVo/intellij-haxe#89]
```shell
/home/as3boyan/jdk1.6.0_38/bin/java -agentlib:jdwp=transport=dt_socket,address=127.0.0.1:47684,suspend=y,server=n -Xmx1024m -Xms512m -XX:MaxPermSize=256m -ea -DHAXELIB_LIST_PATH_SUPPORTED=1 -Xbootclasspath/a:/home/as3boyan/idea-IU-135.1230/lib/boot.jar -Didea.config.path=/home/as3boyan/.IntelliJIdea13/system/plugins-sandbox/config -Didea.system.path=/home/as3boyan/.IntelliJIdea13/system/plugins-sandbox/system -Didea.plugins.path=/home/as3boyan/.IntelliJIdea13/system/plugins-sandbox/plugins -Dsun.awt.disablegrab=true -Dfile.encoding=UTF-8 -classpath /home/as3boyan/jdk1.6.0_38/lib/tools.jar:/home/as3boyan/idea-IU-135.1230/lib/idea_rt.jar:/home/as3boyan/idea-IU-135.1230/lib/idea.jar:/home/as3boyan/idea-IU-135.1230/lib/bootstrap.jar:/home/as3boyan/idea-IU-135.1230/lib/extensions.jar:/home/as3boyan/idea-IU-135.1230/lib/util.jar:/home/as3boyan/idea-IU-135.1230/lib/openapi.jar:/home/as3boyan/idea-IU-135.1230/lib/trove4j.jar:/home/as3boyan/idea-IU-135.1230/lib/jdom.jar:/home/as3boyan/idea-IU-135.1230/lib/log4j.jar com.intellij.idea.Main
Connected to the target VM, address: '127.0.0.1:47684', transport: 'socket'
[   4648]   WARN - openapi.wm.impl.ToolWindowImpl - ToolWindow icons should be 13x13. Please fix jar:file:/home/as3boyan/.IntelliJIdea13/system/plugins-sandbox/plugins/PsiViewer__1_.jar!/images/psiToolWindow.png 
[   4834]   WARN - pl.ExternalResourceManagerImpl - Cannot find standard resource. filename:/META-INF/tapestry_5_0_0.xsd class=class com.intellij.javaee.ResourceRegistrarImpl, classLoader:null 
[   6113]  ERROR - plication.impl.ApplicationImpl - 2 
java.lang.ArrayIndexOutOfBoundsException: 2
	at com.intellij.plugins.haxe.haxelib.HaxelibLibraryCache.<init>(HaxelibLibraryCache.java:79)
	at com.intellij.plugins.haxe.haxelib.HaxelibLibraryCacheManager$SdkEntry.<init>(HaxelibLibraryCacheManager.java:103)
	at com.intellij.plugins.haxe.haxelib.HaxelibLibraryCacheManager.getLibraryCache(HaxelibLibraryCacheManager.java:88)
	at com.intellij.plugins.haxe.haxelib.HaxelibProjectUpdater.syncProjectClasspath(HaxelibProjectUpdater.java:580)
	at com.intellij.plugins.haxe.haxelib.HaxelibProjectUpdater.synchronizeClasspaths(HaxelibProjectUpdater.java:541)
	at com.intellij.plugins.haxe.haxelib.HaxelibProjectUpdater.access$300(HaxelibProjectUpdater.java:81)
	at com.intellij.plugins.haxe.haxelib.HaxelibProjectUpdater$ProjectUpdateQueue.doUpdateWork(HaxelibProjectUpdater.java:1253)
	at com.intellij.plugins.haxe.haxelib.HaxelibProjectUpdater$ProjectUpdateQueue.access$200(HaxelibProjectUpdater.java:1093)
	at com.intellij.plugins.haxe.haxelib.HaxelibProjectUpdater$ProjectUpdateQueue$3$1.run(HaxelibProjectUpdater.java:1235)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$TaskRunnable.run(ProgressManagerImpl.java:471)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$2.run(ProgressManagerImpl.java:178)
	at com.intellij.openapi.progress.ProgressManager.executeProcessUnderProgress(ProgressManager.java:209)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:212)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcess(ProgressManagerImpl.java:171)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$8.run(ProgressManagerImpl.java:380)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:419)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:662)
	at com.intellij.openapi.application.impl.ApplicationImpl$1$1.run(ApplicationImpl.java:149)
[   6114]  ERROR - plication.impl.ApplicationImpl - IntelliJ IDEA 13.1.6  Build #IU-135.1306 
[   6114]  ERROR - plication.impl.ApplicationImpl - JDK: 1.6.0_38-ea 
[   6114]  ERROR - plication.impl.ApplicationImpl - VM: Java HotSpot(TM) 64-Bit Server VM 
[   6114]  ERROR - plication.impl.ApplicationImpl - Vendor: Sun Microsystems Inc. 
[   6114]  ERROR - plication.impl.ApplicationImpl - OS: Linux 
[   6114]  ERROR - plication.impl.ApplicationImpl - Last Action:  
```

**Comment by EBatTiVo** [comment]
Srikanth fixed with change e9dccc7d3983d5c73a8f6ba1c440a80528aae54a.  Should be in build 0.8.1.1.TiVo.ClassHierarchy.8 and later.
